# Generated by Django 4.0.4 on 2022-05-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookingmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bookingmanager',
            name='available_booking_months',
            field=models.IntegerField(default=1, help_text='Насколько месяцев вреред можно забронировать'),
        ),
        migrations.AlterField(
            model_name='bookingmanager',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bookingmanager',
            name='max_appointment_per_time',
            field=models.IntegerField(default=1, help_text='Сколько раз возможно бронирование'),
        ),
        migrations.AlterField(
            model_name='bookingmanager',
            name='period_of_each_booking',
            field=models.CharField(choices=[('5', '5M'), ('10', '10M'), ('15', '15M'), ('20', '20M'), ('25', '25M'), ('30', '30M'), ('35', '35M'), ('40', '40M'), ('45', '45M'), ('60', '1H'), ('75', '1H 15M'), ('90', '1H 30M'), ('105', '1H 45M'), ('120', '2H'), ('150', '2H 30M'), ('180', '3H')], default='60', help_text='Сколько длится бронирование', max_length=3),
        ),
    ]
